### ISSUE TITLE
Support for Europe Chronicle Customers

### ISSUE THREAD

**Issue by secrutiny-jwinchester** [polarityio/chronicle-backstory#2]
The default API endpoint has a base URL of https://backstory.googleapis.com/v1/...
With the advent of Europe tenants this will not work, so please can you add option for "Region" selection to the configuration for Backstory, such that, for Europe tenants the API endpoint base URL can be set to https://europe-backstory.googleapis.com/v1.....
Regards
John

**Comment by sarus** [comment]
@secrutiny-jwinchester Thank you very much for bringing this to our attention.  We just released an update (https://github.com/polarityio/chronicle-backstory/releases/tag/3.1.1-beta) that adds a "Domain" option to the integration options page.  You can set this option to `europe-backstory.googleapis.com` to override the default base URL.  

Unfortunately, we do not have access to a Europe based backstory instance yet so please let us know if the added option works for you.  We're more than happy to make additional updates as needed. 

I'll leave this issue open until we're sure we got it working.

Thank you!
